export const loremIpsum = [
   "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid enim possumus hoc agere divinius? Haeret in salebra. Quae similitudo in genere etiam humano apparet. Duo Reges: constructio interrete. Praeclarae mortes sunt imperatoriae;",
   "Nulla erit controversia. Eam stabilem appellas. Bonum valitudo: miser morbus. Quid enim est a Chrysippo praetermissum in Stoicis? Ne discipulum abducam, times. Illis videtur, qui illud non dubitant bonum dicere -; Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Scrupulum, inquam, abeunti; At certe gravius.",
   "Eam stabilem appellas. Restinguet citius, si ardentem acceperit. At ille pellit, qui permulcet sensum voluptate. Num igitur eum postea censes anxio animo aut sollicito fuisse? Sic enim censent, oportunitatis esse beate vivere.",
   "Est, ut dicis, inquam. Ne in odium veniam, si amicum destitero tueri. Videamus animi partes, quarum est conspectus illustrior; Aufert enim sensus actionemque tollit omnem. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Quo studio Aristophanem putamus aetatem in litteris duxisse?",
   "Ratio quidem vestra sic cogit. Quid dubitas igitur mutare principia naturae? Quod totum contra est. Tollenda est atque extrahenda radicitus. Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba. Bonum patria: miserum exilium.",
   "Omnes enim iucundum motum, quo sensus hilaretur. Sed hoc sane concedamus. Aliter homines, aliter philosophos loqui putas oportere? Duo enim genera quae erant, fecit tria. Sit enim idem caecus, debilis. Facillimum id quidem est, inquam.",
   "Nunc vides, quid faciat. Ac tamen hic mallet non dolere. Nemo igitur esse beatus potest. Quam nemo umquam voluptatem appellavit, appellat;",
   "Zenonis est, inquam, hoc Stoici. Age sane, inquam. Minime vero, inquit ille, consentit.",
   "Comprehensum, quod cognitum non habet? Sed residamus, inquit, si placet. Cupiditates non Epicuri divisione finiebat, sed sua satietate. Primum quid tu dicis breve?",
   "Facillimum id quidem est, inquam. Nunc agendum est subtilius. Expressa vero in iis aetatibus, quae iam confirmatae sunt. Multoque hoc melius nos veriusque quam Stoici. At multis se probavit.",
   "Hoc non est positum in nostra actione. At coluit ipse amicitias. Quid iudicant sensus?",
   "Avaritiamne minuis? Minime vero istorum quidem, inquit. Quae quidem vel cum periculo est quaerenda vobis; Ubi ut eam caperet aut quando? Certe, nisi voluptatem tanti aestimaretis. Esse enim, nisi eris, non potes. Nam quid possumus facere melius? Sed fortuna fortis;",
   "Quid enim possumus hoc agere divinius? Idemne, quod iucunde? Ratio quidem vestra sic cogit. Tum Piso: Quoniam igitur aliquid omnes, quid Lucius noster?",
   "Ratio quidem vestra sic cogit. Primum Theophrasti, Strato, physicum se voluit; Quare attende, quaeso. Immo alio genere; Potius inflammat, ut coercendi magis quam dedocendi esse videantur.",
   "Iam enim adesse poterit. Rationis enim perfectio est virtus; Conferam tecum, quam cuique verso rem subicias; Si mala non sunt, iacet omnis ratio Peripateticorum. Nummus in Croesi divitiis obscuratur, pars est tamen divitiarum. De illis, cum volemus. Dat enim intervalla et relaxat.",
   "Suo genere perveniant ad extremum; Negat esse eam, inquit, propter se expetendam. Quo tandem modo? Sedulo, inquam, faciam.",
   "Equidem e Cn. Honesta oratio, Socratica, Platonis etiam. Quorum altera prosunt, nocent altera. Cur iustitia laudatur?",
   "Tibi hoc incredibile, quod beatissimum. Nunc haec primum fortasse audientis servire debemus. Illi enim inter se dissentiunt. Atqui reperies, inquit, in hoc quidem pertinacem; Quod totum contra est.",
   "Duarum enim vitarum nobis erunt instituta capienda. Stoici scilicet. Consequentia exquirere, quoad sit id, quod volumus, effectum.",
   "Satis est ad hoc responsum. Rhetorice igitur, inquam, nos mavis quam dialectice disputare? Satis est ad hoc responsum.",
   "Quae similitudo in genere etiam humano apparet. Quam si explicavisset, non tam haesitaret. Quae ista amicitia est? Quid vero? Venit ad extremum; Hoc tu nunc in illo probas.",
   "Summum a vobis bonum voluptas dicitur. Quod cum dixissent, ille contra. Tum ille: Ain tandem? Bonum integritas corporis: misera debilitas.",
   "Quod autem principium officii quaerunt, melius quam Pyrrho; Invidiosum nomen est, infame, suspectum. Beatus autem esse in maximarum rerum timore nemo potest. Quod cum dixissent, ille contra.",
   "Bonum incolumis acies: misera caecitas. Cave putes quicquam esse verius. Restatis igitur vos; Immo videri fortasse.",
   "Non risu potius quam oratione eiciendum? Nos commodius agimus. Videamus animi partes, quarum est conspectus illustrior; Sed fortuna fortis; Cur iustitia laudatur?",
   "Iam id ipsum absurdum, maximum malum neglegi. Omnia contraria, quos etiam insanos esse vultis. Falli igitur possumus. Neutrum vero, inquit ille. Confecta res esset.",
   "Hoc ipsum elegantius poni meliusque potuit. Immo videri fortasse. Graece donan, Latine voluptatem vocant. Prodest, inquit, mihi eo esse animo. Idemne, quod iucunde? Et ille ridens: Video, inquit, quid agas;",
   "Heri, inquam, ludis commissis ex urbe profectus veni ad vesperum. Quid iudicant sensus? Frater et T. Sequitur disserendi ratio cognitioque naturae; Cur post Tarentum ad Archytam? Itaque his sapiens semper vacabit.",
   "Deprehensus omnem poenam contemnet. Aperiendum est igitur, quid sit voluptas; Quo studio Aristophanem putamus aetatem in litteris duxisse? Quam nemo umquam voluptatem appellavit, appellat;",
   "Dat enim intervalla et relaxat. Apparet statim, quae sint officia, quae actiones. Hic ambiguo ludimur. Quis est tam dissimile homini. Igitur neque stultorum quisquam beatus neque sapientium non beatus. Suo genere perveniant ad extremum; Sed haec nihil sane ad rem; Cur iustitia laudatur?",
   "Prodest, inquit, mihi eo esse animo. Sic enim censent, oportunitatis esse beate vivere. An haec ab eo non dicuntur? Cum praesertim illa perdiscere ludus esset. An tu me de L.",
   "Aliter homines, aliter philosophos loqui putas oportere? Ita graviter et severe voluptatem secrevit a bono. Hoc ipsum elegantius poni meliusque potuit. Immo alio genere; Sit enim idem caecus, debilis. Non laboro, inquit, de nomine. Invidiosum nomen est, infame, suspectum. Ergo ita: non posse honeste vivi, nisi honeste vivatur?",
   "Ostendit pedes et pectus. Quodsi ipsam honestatem undique pertectam atque absolutam. Non igitur bene. Estne, quaeso, inquam, sitienti in bibendo voluptas?",
   "Cyrenaici quidem non recusant; Hoc non est positum in nostra actione. Inde igitur, inquit, ordiendum est. Quam si explicavisset, non tam haesitaret. Iam id ipsum absurdum, maximum malum neglegi.",
   "At ego quem huic anteponam non audeo dicere; Certe, nisi voluptatem tanti aestimaretis. Mihi enim satis est, ipsis non satis. Sic enim censent, oportunitatis esse beate vivere.",
   "Negabat igitur ullam esse artem, quae ipsa a se proficisceretur; Vestri haec verecundius, illi fortasse constantius. Quid autem habent admirationis, cum prope accesseris? Ergo ita: non posse honeste vivi, nisi honeste vivatur? Hoc loco tenere se Triarius non potuit. Quonam, inquit, modo? At hoc in eo M. Mihi enim satis est, ipsis non satis.",
   "Quid ait Aristoteles reliquique Platonis alumni? Maximas vero virtutes iacere omnis necesse est voluptate dominante. Iam in altera philosophiae parte.",
   "Non semper, inquam; Primum in nostrane potestate est, quid meminerimus? Iam in altera philosophiae parte. Maximus dolor, inquit, brevis est. Ea possunt paria non esse. Facillimum id quidem est, inquam.",
   "Diodorus, eius auditor, adiungit ad honestatem vacuitatem doloris. An vero, inquit, quisquam potest probare, quod perceptfum, quod. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Quamquam id quidem licebit iis existimare, qui legerint. Idem adhuc; Quae similitudo in genere etiam humano apparet.",
   "At hoc in eo M. Tum Torquatus: Prorsus, inquit, assentior; Itaque his sapiens semper vacabit. Mihi enim erit isdem istis fortasse iam utendum.",
   "Quid sequatur, quid repugnet, vident. Sed plane dicit quod intellegit. Tubulo putas dicere? Avaritiamne minuis? Hoc Hieronymus summum bonum esse dixit.",
   "Obsecro, inquit, Torquate, haec dicit Epicurus? Nos commodius agimus. Quare attende, quaeso. Certe non potest. Sed haec omittamus; Ut optime, secundum naturam affectum esse possit.",
   "Comprehensum, quod cognitum non habet? Haec igitur Epicuri non probo, inquam. Addidisti ad extremum etiam indoctum fuisse. Duarum enim vitarum nobis erunt instituta capienda.",
   "Aliter homines, aliter philosophos loqui putas oportere? Ea possunt paria non esse. Iam contemni non poteris. Sed haec quidem liberius ab eo dicuntur et saepius. Comprehensum, quod cognitum non habet? Quis non odit sordidos, vanos, leves, futtiles? Beatus sibi videtur esse moriens. Haec dicuntur inconstantissime.",
   "Nam, ut sint illa vendibiliora, haec uberiora certe sunt. Moriatur, inquit. Neutrum vero, inquit ille. Sed ad rem redeamus;",
   "Eaedem res maneant alio modo. Tria genera bonorum; Cur haec eadem Democritus? Haec quo modo conveniant, non sane intellego. Nos commodius agimus. At ille pellit, qui permulcet sensum voluptate.",
   "Refert tamen, quo modo. Ubi ut eam caperet aut quando? Audeo dicere, inquit. Sed in rebus apertissimis nimium longi sumus.",
   "Quam nemo umquam voluptatem appellavit, appellat; Laboro autem non sine causa; Tollenda est atque extrahenda radicitus. Quantum Aristoxeni ingenium consumptum videmus in musicis? Expectoque quid ad id, quod quaerebam, respondeas. Sed ad bona praeterita redeamus.",
   "Quorum altera prosunt, nocent altera. Aliter enim explicari, quod quaeritur, non potest. Illa tamen simplicia, vestra versuta. Non semper, inquam; Claudii libidini, qui tum erat summo ne imperio, dederetur.",
   "Tu quidem reddes; Sed hoc sane concedamus. Minime vero istorum quidem, inquit. Res enim concurrent contrariae. Tu vero, inquam, ducas licet, si sequetur; Certe, nisi voluptatem tanti aestimaretis. Indicant pueri, in quibus ut in speculis natura cernitur.",
   "Bonum incolumis acies: misera caecitas. Venit ad extremum; Nihil enim hoc differt.",
   "Quonam, inquit, modo? Proclivi currit oratio. Cur post Tarentum ad Archytam? Beatus autem esse in maximarum rerum timore nemo potest.",
   "Eam tum adesse, cum dolor omnis absit; Eam stabilem appellas. Et quidem, inquit, vehementer errat; Quod vestri non item. Nam Pyrrho, Aristo, Erillus iam diu abiecti.",
   "Utilitatis causa amicitia est quaesita. Quid autem habent admirationis, cum prope accesseris? Sed ad illum redeo. Maximus dolor, inquit, brevis est. Multoque hoc melius nos veriusque quam Stoici.",
   "Erat enim Polemonis. Scaevolam M. Non est igitur voluptas bonum. Omnes enim iucundum motum, quo sensus hilaretur. Ut in geometria, prima si dederis, danda sunt omnia.",
   "Quid adiuvas? Eiuro, inquit adridens, iniquum, hac quidem de re; Sed haec omittamus; Simus igitur contenti his.",
   "Invidiosum nomen est, infame, suspectum. Omnia contraria, quos etiam insanos esse vultis. Sed residamus, inquit, si placet. Videamus animi partes, quarum est conspectus illustrior; Si longus, levis. Non igitur bene.",
   "Vide, quantum, inquam, fallare, Torquate. Tum ille: Ain tandem? Sic enim censent, oportunitatis esse beate vivere. Nihil sane. Tanta vis admonitionis inest in locis; Ego vero isti, inquam, permitto.",
   "Cur id non ita fit? At enim sequor utilitatem. Ut in geometria, prima si dederis, danda sunt omnia. Ita graviter et severe voluptatem secrevit a bono. Sed ne, dum huic obsequor, vobis molestus sim. Hunc vos beatum;",
   "Haec dicuntur inconstantissime. Videsne quam sit magna dissensio?",
   "Vitiosum est enim in dividendo partem in genere numerare. Sed in rebus apertissimis nimium longi sumus. Tubulo putas dicere? Quod cum dixissent, ille contra.",
   "Non est igitur summum malum dolor. Falli igitur possumus. Memini me adesse P. Primum Theophrasti, Strato, physicum se voluit; Igitur ne dolorem quidem. Atqui reperies, inquit, in hoc quidem pertinacem;",
   "Quid de Platone aut de Democrito loquar? ALIO MODO. Quae duo sunt, unum facit. Sumenda potius quam expetenda. Oratio me istius philosophi non offendit; Nam quid possumus facere melius? Id mihi magnum videtur.",
   "Quare ad ea primum, si videtur; Nos commodius agimus.",
   "Quo modo? Quis non odit sordidos, vanos, leves, futtiles? Negat esse eam, inquit, propter se expetendam.",
   "Haec para/doca illi, nos admirabilia dicamus. Conferam tecum, quam cuique verso rem subicias;",
   "Quamquam tu hanc copiosiorem etiam soles dicere. Sed ego in hoc resisto; Iam in altera philosophiae parte. Easdemne res?",
   "Maximus dolor, inquit, brevis est. Nemo igitur esse beatus potest. Ut aliquid scire se gaudeant? Sit enim idem caecus, debilis. Quid sequatur, quid repugnet, vident. Sed fortuna fortis; Vide, quantum, inquam, fallare, Torquate. Eam tum adesse, cum dolor omnis absit;",
   "Nunc de hominis summo bono quaeritur; Nam Pyrrho, Aristo, Erillus iam diu abiecti. Tuo vero id quidem, inquam, arbitratu. Est, ut dicis, inquit; Quid est igitur, inquit, quod requiras? At hoc in eo M.",
   "Nemo igitur esse beatus potest. Hoc simile tandem est? Nihil opus est exemplis hoc facere longius. Quae similitudo in genere etiam humano apparet. In schola desinis. Quis negat? Primum quid tu dicis breve?",
   "Esse enim quam vellet iniquus iustus poterat inpune. Quod cum dixissent, ille contra. Et nemo nimium beatus est; Expectoque quid ad id, quod quaerebam, respondeas.",
   "Hoc enim constituto in philosophia constituta sunt omnia. Quo tandem modo?",
   "Sequitur disserendi ratio cognitioque naturae; Teneo, inquit, finem illi videri nihil dolere. Haec igitur Epicuri non probo, inquam. Summum ením bonum exposuit vacuitatem doloris; Quae autem natura suae primae institutionis oblita est?",
   "Restatis igitur vos; Huius, Lyco, oratione locuples, rebus ipsis ielunior. Praeteritis, inquit, gaudeo. Efficiens dici potest.",
   "Rhetorice igitur, inquam, nos mavis quam dialectice disputare? Collige omnia, quae soletis: Praesidium amicorum. Verum hoc idem saepe faciamus. Sed ille, ut dixi, vitiose. Deinde dolorem quem maximum? Videsne quam sit magna dissensio?",
   "Quo igitur, inquit, modo? Age, inquies, ista parva sunt. Aeque enim contingit omnibus fidibus, ut incontentae sint. Quam si explicavisset, non tam haesitaret.",
   "Nam de isto magna dissensio est. Quid nunc honeste dicit? Aliter enim nosmet ipsos nosse non possumus. Cur deinde Metrodori liberos commendas?",
   "Quae cum dixisset, finem ille. Explanetur igitur. Omnis enim est natura diligens sui. Murenam te accusante defenderem.",
   "Praeclare hoc quidem. Erat enim res aperta. Istam voluptatem, inquit, Epicurus ignorat? Quid est igitur, inquit, quod requiras? Traditur, inquit, ab Epicuro ratio neglegendi doloris.",
   "Non laboro, inquit, de nomine. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse;",
   "Tu quidem reddes; Sed ad illum redeo. Tu quidem reddes; Tu quidem reddes;",
   "Cur deinde Metrodori liberos commendas? Sullae consulatum?",
   "Atqui reperies, inquit, in hoc quidem pertinacem; Nos commodius agimus. Cave putes quicquam esse verius. Verum hoc idem saepe faciamus. Sed ad bona praeterita redeamus. Sed haec in pueris;",
   "Non potes, nisi retexueris illa. Tu vero, inquam, ducas licet, si sequetur; At ille pellit, qui permulcet sensum voluptate. Quis Aristidem non mortuum diligit?",
   "Quis hoc dicit? Que Manilium, ab iisque M. Illi enim inter se dissentiunt. Videmus igitur ut conquiescere ne infantes quidem possint. Si longus, levis dictata sunt. Idemne, quod iucunde? Eam stabilem appellas.",
   "Sed mehercule pergrata mihi oratio tua. Quae cum dixisset, finem ille. Quamquam te quidem video minime esse deterritum. Nihil opus est exemplis hoc facere longius. Praeclare hoc quidem. Id Sextilius factum negabat.",
   "Maximus dolor, inquit, brevis est. Quid de Platone aut de Democrito loquar? Tamen a proposito, inquam, aberramus. Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba.",
   "Istam voluptatem perpetuam quis potest praestare sapienti? Sequitur disserendi ratio cognitioque naturae; Nam Pyrrho, Aristo, Erillus iam diu abiecti. Summum a vobis bonum voluptas dicitur. Age sane, inquam.",
   "Quamquam id quidem licebit iis existimare, qui legerint. An tu me de L. Sed eum qui audiebant, quoad poterant, defendebant sententiam suam. Iam enim adesse poterit.",
   "Sed quid sentiat, non videtis. Duo enim genera quae erant, fecit tria. Quare attende, quaeso. Magna laus. Qui est in parvis malis. Sic enim censent, oportunitatis esse beate vivere.",
   "Videsne, ut haec concinant? Quid Zeno? Quamquam te quidem video minime esse deterritum. Prodest, inquit, mihi eo esse animo. Quae quidem vel cum periculo est quaerenda vobis; Id enim natura desiderat. Ergo ita: non posse honeste vivi, nisi honeste vivatur? Illi enim inter se dissentiunt.",
   "Quare attende, quaeso. Beatus sibi videtur esse moriens. Sed quot homines, tot sententiae; Dempta enim aeternitate nihilo beatior Iuppiter quam Epicurus; Dat enim intervalla et relaxat. Age sane, inquam.",
   "Praeteritis, inquit, gaudeo. Quis enim redargueret? Quod ea non occurrentia fingunt, vincunt Aristonem; Sed videbimus.",
   "Quid censes in Latino fore? Sed ille, ut dixi, vitiose. Nulla erit controversia. Itaque ab his ordiamur.",
   "Respondeat totidem verbis. Non semper, inquam; Quid ad utilitatem tantae pecuniae? Murenam te accusante defenderem. Negare non possum.",
   "Scrupulum, inquam, abeunti; A mene tu? Quonam modo? Tu quidem reddes;",
   "Tu vero, inquam, ducas licet, si sequetur; Haec para/doca illi, nos admirabilia dicamus. Ea possunt paria non esse. Ac tamen hic mallet non dolere.",
   "An est aliquid, quod te sua sponte delectet? Maximus dolor, inquit, brevis est. Duarum enim vitarum nobis erunt instituta capienda. Quamquam tu hanc copiosiorem etiam soles dicere.",
   "Respondeat totidem verbis. Ne in odium veniam, si amicum destitero tueri. An hoc usque quaque, aliter in vita? Quid est igitur, inquit, quod requiras?",
   "Duo enim genera quae erant, fecit tria. Nihil enim hoc differt. Dici enim nihil potest verius. Erit enim mecum, si tecum erit."
];
