name: CodeChecks
on: [pull_request]
jobs:
   lint:
      runs-on: ubuntu-22.04
      steps:
         - name: Get Codebase
           uses: actions/checkout@v3
         - name: Install Node
           uses: actions/setup-node@v3
           with:
              node-version: "16"
              cache: "npm"
         - name: Install Modules
           run: npm ci
         - name: Run ESLint
           run: npm run lint:strict

   format:
      runs-on: ubuntu-22.04
      steps:
         - name: Get Codebase
           uses: actions/checkout@v3
         - name: Install Node
           uses: actions/setup-node@v3
           with:
              node-version: "16"
              cache: "npm"
         - name: Install Modules
           run: npm ci
         - name: Run Prettier Check
           run: npm run format:check

   test:
      runs-on: ubuntu-22.04
      steps:
         - name: Get Codebase
           uses: actions/checkout@v3
         - name: Install Node
           uses: actions/setup-node@v3
           with:
              node-version: "16"
              cache: "npm"
         - name: Install Modules
           run: npm ci
         - name: Generate Routes
           run: npm run routes
         - name: Build limble-tree
           run: npm run ng build -- limble-tree
         - name: Test limble-tree
           run: npm run ng test -- limble-tree --no-watch --no-progress --browsers=ChromeHeadless
         - name: Test sandbox
           run: npm run ng test -- sandbox --no-watch --no-progress --browsers=ChromeHeadless
